##Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [3]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
x = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
x_train

array([[-0.47340426,  0.21135317, -1.28167799, ...,  0.32300687,
        -0.21763496,  0.35487339],
       [ 0.61755799, -1.26955565,  1.47424891, ..., -1.0432359 ,
         1.52972922,  1.19756499],
       [-0.4159852 ,  2.02135285, -1.07753526, ...,  0.51818441,
        -0.5671078 , -0.58145062],
       ...,
       [-0.70308053,  0.86953487, -0.97546389, ...,  0.71336195,
        -0.33412591, -0.20692102],
       [ 1.82335838, -0.66622243,  1.27010618, ..., -0.32758492,
         1.29674733,  0.54213819],
       [ 0.38788173, -0.2822831 ,  0.24939251, ...,  0.06277015,
        -0.21763496, -0.95598022]])

In [11]:
x_test

array([[ 2.68464438, -1.1598587 ,  1.93357007, ..., -1.69382769,
        -0.27588043,  0.16760858],
       [ 2.51238718,  0.3758986 ,  1.11699913, ..., -1.10829508,
        -0.50886232,  0.91666779],
       [-0.47340426,  1.30832267, -0.36303569, ..., -0.71794   ,
        -0.45061685, -1.14324502],
       ...,
       [ 0.2730436 , -0.7210709 ,  0.65767798, ...,  0.84348031,
        -0.10114401, -1.14324502],
       [-0.0714708 , -0.7210709 ,  0.86182071, ...,  1.42901292,
        -0.27588043,  0.07397618],
       [ 1.59368212, -0.77591938,  1.37217755, ..., -1.17335426,
        -0.85833516, -0.86234782]])

##Train on Different Algorithms

In [12]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [14]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel = 'linear')
ks_cla = SVC(kernel = 'rbf')

In [15]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [19]:
l_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  1,  7,  4,  1,  0],
       [ 0,  0, 95, 37,  0,  0],
       [ 0,  0, 44, 80, 11,  0],
       [ 0,  0,  1, 20, 12,  0],
       [ 0,  0,  0,  2,  3,  0]])

In [20]:
k_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  1,  6,  6,  0,  0],
       [ 0,  1, 90, 38,  2,  1],
       [ 0,  1, 48, 75, 11,  0],
       [ 0,  0,  4, 15, 14,  0],
       [ 0,  0,  0,  2,  3,  0]])

In [21]:
d_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 1,  1,  5,  3,  3,  0],
       [ 0,  2, 89, 37,  4,  0],
       [ 0,  3, 35, 80, 13,  4],
       [ 0,  0,  2, 13, 18,  0],
       [ 0,  0,  1,  3,  1,  0]])

In [22]:
r_c

array([[  0,   1,   0,   1,   0,   0],
       [  0,   0,   9,   3,   1,   0],
       [  0,   0, 100,  32,   0,   0],
       [  0,   0,  34,  90,  11,   0],
       [  0,   0,   1,  15,  17,   0],
       [  0,   0,   0,   0,   5,   0]])

In [23]:
s_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  9,  4,  0,  0],
       [ 0,  0, 94, 38,  0,  0],
       [ 0,  0, 50, 85,  0,  0],
       [ 0,  0,  1, 32,  0,  0],
       [ 0,  0,  0,  5,  0,  0]])

In [24]:
ks_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0, 10,  2,  1,  0],
       [ 0,  0, 96, 36,  0,  0],
       [ 0,  0, 49, 78,  8,  0],
       [ 0,  0,  3, 15, 15,  0],
       [ 0,  0,  0,  2,  3,  0]])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [27]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.5875
KNN: 0.5625
Decision Tree: 0.5875
Random Forest: 0.646875
Linear SVC: 0.559375
Kernel SVC: 0.5875
